spring:
  application:
    name: sca-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: jd:8848
server:
  port: 10107

feign:
  client:
    config:
      default:  #服务名，填写default为所有服务
        connectTimeout: 3000
        readTimeout: 12000
